### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by actswartz** [schornig/viptela-sdwan-stats-collector#1]
First, thank you so very much.
I am having trouble getting this working.
I get the message:
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/root/sdwan-integration-with-influxdb-grafana/venv/lib/python3.7/site-packages/timeloop/job.py", line 19, in run
    self.execute(*self.args, **self.kwargs)
  File "viptela-collector.py", line 262, in Periodic_1s
    TaskScheduller(vm=vManage_API, db=influx_db, measurements=config['Measurements'])
  File "viptela-collector.py", line 237, in TaskScheduller
    data_points += getattr(vm, query_type)(query_data=query_data)
  File "viptela-collector.py", line 56, in SimpleAPICall
    tags[tag.replace('-', '_')] = entry[tag]
KeyError: 'site-id'

Any ideas?

Thanks,

John

**Comment by schornig** [comment]
Fixed in latest version.
